// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildHTML(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['BuildHTML'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LoadFromIBM(arg1, arg2) {
  return window['go']['main']['App']['LoadFromIBM'](arg1, arg2);
}

export function MergeFiles() {
  return window['go']['main']['App']['MergeFiles']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function ParseFile() {
  return window['go']['main']['App']['ParseFile']();
}

export function ParseText(arg1) {
  return window['go']['main']['App']['ParseText'](arg1);
}

export function SaveAndOpenHTML(arg1, arg2) {
  return window['go']['main']['App']['SaveAndOpenHTML'](arg1, arg2);
}

export function SaveHTML(arg1, arg2) {
  return window['go']['main']['App']['SaveHTML'](arg1, arg2);
}

export function SaveRawLog(arg1, arg2) {
  return window['go']['main']['App']['SaveRawLog'](arg1, arg2);
}
