// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildHTML(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean):Promise<string>;

export function LoadFromIBM(arg1:string,arg2:string):Promise<main.ParseResult>;

export function MergeFiles():Promise<main.ParseResult>;

export function OpenInBrowser(arg1:string):Promise<string>;

export function ParseFile():Promise<main.ParseResult>;

export function ParseText(arg1:string):Promise<main.ParseResult>;

export function SaveAndOpenHTML(arg1:string,arg2:string):Promise<string>;

export function SaveHTML(arg1:string,arg2:string):Promise<string>;

export function SaveRawLog(arg1:string,arg2:string):Promise<string>;
